openapi: 3.0.1
info:
  title: Ecommerce API
  version: 1.0.0

paths:
  /price:
    get:
      tags:
        - Price
      summary: Get price by id product, id brand and application date
      operationId: getPrice
      parameters:
        - name: applicationDate
          description: Application date (format 'yyyy-MM dd HH:mm:ss')
          in: query
          required: true
          schema:
            type: string
            pattern: '^\d{4}-\d{2}-\d{2} \d{2}\:\d{2}\:\d{2}$'
            example: '2020-06-14 00.00.00'
        - name: productId
          description: Product Id
          in: query
          required: true
          schema:
            type: integer
            minimum: 1
        - name: brandId
          description: Brand Id
          in: query
          required: true
          schema:
            type: integer
            minimum: 1

      responses:
        "200":
          description: Response OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PriceResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    PriceResponse:
      type: object
      properties:
        productId:
          description: Product identifier
          type: integer
        brandId:
          description: Brand identifier
          type: integer
        rate:
          description: Rate to be apply
          type: integer
        startDate:
          description: Start date of the pirce
          type: string
        endDate:
          description: End date of the pirce
          type: string
        price:
          description: Price amount
          type: number
          format: double
        currency:
          description: ISO Currency
          type: string
      required:
        - productId
        - brandId
        - rate
        - startDate
        - endDate
        - price
        - currency

    ErrorResponse:
      type: object
      properties:
        title:
          type: string
        errorCode:
          type: string
        message:
          type: string
      required:
        - message
